name: Deploy Environment
on:
  pull_request:
    branch : ["prod", "dev"]
                         
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print Branch Name
      run: echo "The branch name is ${{ github.ref_name }}"
